package repository

func principalities() []Principality {
	return []Principality{
		{
			PrincipalityID:      1,
			PrincipalityName:    "Киевское княжество",
			PrincipalitySummary: "Стольный град Киев - крупнейший укреплённый центр Древней Руси. Город Владимира, город Ярослава и город Изяслава вместе с Подолом дают около 300 гектаров укреплённой площади, что делает Киев верхней границей шкалы при любой оценке городского населения домонгольской Руси.",
			PrincipalityStatus:  PrincipalityStatusPublished,
			FoundingDate:        FoundedInYear(882),
			LandCoefficient:     0.55,
			ImageKey:            "kiev.jpg",
			VideoKey:            "kiev.mp4",
			LikedBy:             []int{1, 8},
		},
		{
			PrincipalityID:      4,
			PrincipalityName:    "Владимиро-Суздальское княжество",
			PrincipalitySummary: "Владимир-на-Клязьме при Андрее Боголюбском вырос до 145 гектаров: Печерний город, Новый город и Ветчаной город с валами и Золотыми воротами. Столица Северо-Восточной Руси, застройка усадебная и плотная.",
			PrincipalityStatus:  PrincipalityStatusPublished,
			FoundingDate:        FoundedInYear(1157),
			LandCoefficient:     0.55,
			ImageKey:            "vladimir.jpg",
			VideoKey:            "vladimir.mp4",
			LikedBy:             []int{3, 5},
		},
		{
			PrincipalityID:      5,
			PrincipalityName:    "Смоленское княжество",
			PrincipalitySummary: "Смоленск занимал около 100 гектаров на днепровских холмах. Ключевой пункт пути из варяг в греки, с развитым ремесленным посадом и десятками каменных храмов домонгольской постройки.",
			PrincipalityStatus:  PrincipalityStatusPublished,
			FoundingDate:        FoundedInYear(1054),
			LandCoefficient:     0.55,
			ImageKey:            "smolensk.jpg",
			VideoKey:            "smolensk.mp4",
			LikedBy:             []int{2, 7, 9},
		},
		{
			PrincipalityID:      6,
			PrincipalityName:    "Переславль-Залесское княжество",
			PrincipalitySummary: "Переславль-Залесский основан Юрием Долгоруким в 1152 году: земляной вал длиной около двух с половиной километров охватывает примерно 40 гектаров. Валы сохранились по всему периметру, поэтому площадь измеряется не по реконструкции, а по существующему укреплению.",
			PrincipalityStatus:  PrincipalityStatusPublished,
			FoundingDate:        FoundedInYear(1152),
			LandCoefficient:     0.30,
			ImageKey:            "pereslavl_zalessky.jpg",
			VideoKey:            "pereslavl_zalessky.mp4",
			LikedBy:             []int{4},
		},
		{
			PrincipalityID:      7,
			PrincipalityName:    "Переяславское княжество",
			PrincipalitySummary: "Переяславль Южный на Трубеже - около 80 гектаров. Третий стол Русской земли наряду с Киевом и Черниговом, но постоянные половецкие набеги держали застройку менее плотной, чем в глубине страны.",
			PrincipalityStatus:  PrincipalityStatusPublished,
			FoundingDate:        FoundedInYear(1054),
			LandCoefficient:     0.45,
			ImageKey:            "pereyaslavl.jpg",
			VideoKey:            "pereyaslavl.mp4",
			LikedBy:             []int{6, 8},
		},
		{
			PrincipalityID:      8,
			PrincipalityName:    "Полоцкое княжество",
			PrincipalitySummary: "Полоцк на Западной Двине - около 58 гектаров. Древнейший центр кривичей, рано обособившийся от Киева; Софийский собор и детинец на высоком берегу задают компактную планировку.",
			PrincipalityStatus:  PrincipalityStatusPublished,
			FoundingDate:        FoundedInYear(988),
			LandCoefficient:     0.45,
			ImageKey:            "polotsk.jpg",
			VideoKey:            "polotsk.mp4",
			LikedBy:             []int{9},
		},
		{
			PrincipalityID:      9,
			PrincipalityName:    "Галицкое княжество",
			PrincipalitySummary: "",
			PrincipalityStatus:  PrincipalityStatusDraft,
			FoundingDate:        FoundingDate{},
			LandCoefficient:     0,
			ImageKey:            "galich.jpg",
			VideoKey:            "galich.mp4",
			LikedBy:             []int{},
		},
		{
			PrincipalityID:      10,
			PrincipalityName:    "Муромо-Рязанское княжество",
			PrincipalitySummary: "Старая Рязань на Оке - около 53 гектаров. Столица княжества, разорённая в 1237 году и после этого не восстановленная, поэтому её планировка изучена археологически лучше многих действующих городов.",
			PrincipalityStatus:  PrincipalityStatusRemoved,
			FoundingDate:        FoundedInYear(1097),
			LandCoefficient:     0.45,
			ImageKey:            "ryazan.jpg",
			VideoKey:            "ryazan.mp4",
			LikedBy:             []int{5},
		},
	}
}
